services:
  allensdk_jupyter:
    build:
      context: .
      dockerfile: Dockerfile # Use the Dockerfile in the current context
    volumes:
      - ./allensdk_export:/src/allensdk_export # Mount code directory
      - ./data:/src/data # Mount data directory
      - ./experanto:/src/experanto # Mount experanto
      - ./sensorium_2023:/src/sensorium_2023 # Mount sensorium
      - ./neuralpredictors:/src/neuralpredictors # Mount neural_predictors
    ports:
      - "8888:8888" # Expose port for Jupyter Notebook
    environment:
      - PYTHONBUFFERED=1 # Ensures Python output is sent straight to terminal (avoiding buffering)
